// Your photo gallery configuration
// cloud name: Dashboard → Account Details (or the segment after res.cloudinary.com/ in a delivery URL)
const CLOUDINARY_CLOUD_NAME = 'deezpztlx';

// publicId must match Cloudinary exactly (copy from Media Library or the path after /upload/ in a delivery URL).
// Include folder prefix if you use folders (e.g. fotos/name). Include the _suffix Cloudinary added if present.

const photos = [
    { publicId: 'rj_r5gop8', title: 'Rio de Janeiro', location: 'Brasil' },
    { publicId: 'vista_chinesa_xbaaf6', title: 'Vista Chinesa', location: 'Brasil' },
    { publicId: 'banff_xcehev', title: 'Banff', location: 'Canada' },
    { publicId: 'seljalandsfoss_lewujm', title: 'Seljalandsfoss', location: 'Ísland' },
    { publicId: 'cliffs_hgrldr', title: 'Cliffs', location: 'Ísland' },
    { publicId: 'hvalnes_dwljzw', title: 'Hvalnes', location: 'Ísland' },
    { publicId: 'jökulsárgljúfur_plpfiw', title: 'Jökulsárgljúfur', location: 'Ísland' },
    { publicId: 'aurora_aoxclg', title: 'Aurora', location: 'Ísland' },
    { publicId: 'jordan_river_npwxxb', title: 'Jordan River', location: 'Canada' },
    { publicId: 'gran_roque_gtquuw', title: 'Gran Roque Pelicans', location: 'Venezuela' },
    { publicId: 'gran_roque_sunset_ds7ytg', title: 'Gran Roque Sunset', location: 'Venezuela' },
    { publicId: 'dos_mosquises_idvg5s', title: 'Dos Mosquises', location: 'Venezuela' },
    { publicId: 'la_guaira_1_ny9mrx', title: 'La Guaira 1', location: 'Venezuela' },
    { publicId: 'la_guaira_2_qwzm4p', title: 'La Guaira 2', location: 'Venezuela' },
    { publicId: 'santa_teresa_u7abx6', title: 'Santa Teresa', location: 'Venezuela' },
    { publicId: 'eclipse_yhv2sh', title: 'Eclipse', location: 'Canada' },
    { publicId: 'cape_spear_n62imu', title: 'Cape Spear', location: 'Canada' },
    { publicId: 'skerwink_1_pfsbxx', title: 'Skerwink Trail 1', location: 'Canada' },
    { publicId: 'skerwink_2_fyusom', title: 'Skerwink Trail 2', location: 'Canada' },
    { publicId: 'puffin_inb8w1', title: 'Puffin', location: 'Canada' },
    { publicId: 'puffins_os5bs7', title: 'Puffins', location: 'Canada' },
    { publicId: 'nl_cliffs_wza10a', title: 'Cliffs', location: 'Canada' },
    { publicId: 'nl_hut_w7jhh2', title: 'Hut', location: 'Canada' },
    { publicId: 'nl_fox_dqifei', title: 'Fox', location: 'Canada' },
    { publicId: 'riverdale_ecv8w3', title: 'Riverdale', location: 'Canada' },
    { publicId: 'toronto_cr3bim', title: 'CN Tower', location: 'Canada' },
    { publicId: 'la_fortuna_ienfvf', title: 'La Fortuna', location: 'Costa Rica' },
    { publicId: 'arenal_neqrk3', title: 'Arenal', location: 'Costa Rica' },
    { publicId: 'el_tigre_og5sgo', title: 'El Tigre', location: 'Costa Rica' },
    { publicId: 'quetzal_nnhgq5', title: 'Quetzal', location: 'Costa Rica' },
    { publicId: 'candelita_collareja_kup2v0', title: 'Candelita Collareja', location: 'Costa Rica' },
    { publicId: 'espadilla_etvcx5', title: 'Espadilla', location: 'Costa Rica' },
    { publicId: 'mono_ardilla_fhhvho', title: 'Mono Ardilla', location: 'Costa Rica' },
    { publicId: 'bertioga_1_h5av5y', title: 'Bertioga 1', location: 'Brasil' },
    { publicId: 'bertioga_2_hrrh8y', title: 'Bertioga 2', location: 'Brasil' },
    { publicId: 'taipei_1_z4tdm8', title: 'Xiangshan Park', location: '臺灣' },
    { publicId: 'taipei_2_gvlgcd', title: 'Xiangshan Park Basketball', location: '臺灣' },
    { publicId: 'taipei_101_q9vpgi', title: 'Taipei 101', location: '臺灣' },
    { publicId: 'grand_palace_zsepyj', title: 'Grand Palace', location: 'ประเทศไทย' },
    { publicId: 'bangkok_ba6wsx', title: 'Bangkok', location: 'ประเทศไทย' },
    { publicId: 'hanoi_svgmlz', title: 'Hà Nội', location: 'Việt Nam' },
    { publicId: 'ha_long_sqdk2m', title: 'Hạ Long Bay', location: 'Việt Nam' },
    { publicId: 'ha_long_fishermen_lxbcxl', title: 'Hạ Long Fishermen', location: 'Việt Nam' },
    { publicId: 'trang_an_ksmprm', title: 'Tràng An 1', location: 'Việt Nam' },
    { publicId: 'trang_an_2_l0dwzi', title: 'Tràng An 2', location: 'Việt Nam' },
    { publicId: 'mandarins_ithpk3', title: 'Mandarins', location: 'Việt Nam' },
    { publicId: 'hang_mua_viewpoint_zsg5rg', title: 'Hang Múa Viewpoint', location: 'Việt Nam' },
    { publicId: 'bich_dong_glcl7q', title: 'Bích Động', location: 'Việt Nam' },
    { publicId: 'tam_coc_lcmxuf', title: 'Tam Cốc Ricefields', location: 'Việt Nam' },
    { publicId: 'tam_coc_road_i5l9wz', title: 'Tam Cốc Road', location: 'Việt Nam' },
    { publicId: 'tam_coc_sunset_eazl6d', title: 'Tam Cốc Sunset', location: 'Việt Nam' },
    { publicId: 'pu_luong_valley_owtkpa', title: 'Pù Luông Valley', location: 'Việt Nam' },
    { publicId: 'pu_luong_terraces_vwssrr', title: 'Pù Luông Terraces', location: 'Việt Nam' },
    { publicId: 'coron_jkbqbl', title: 'Coron', location: 'Pilipinas' },
    { publicId: 'palawan_expedition_xuicsl', title: 'Palawan', location: 'Pilipinas' },
];
