// Your photo gallery configuration
// cloud name: Dashboard → Account Details (or the segment after res.cloudinary.com/ in a delivery URL)
const CLOUDINARY_CLOUD_NAME = 'deezpztlx';

// publicId must match Cloudinary exactly (copy from Media Library or the path after /upload/ in a delivery URL).
// Include folder prefix if you use folders (e.g. fotos/name). Include the _suffix Cloudinary added if present.

const photos = [
    { publicId: 'bich_dong_glcl7q', title: 'Bich Dong', location: 'Vietnam' },
    { publicId: 'tam_coc_lcmxuf', title: 'Tam Coc Ricefields', location: 'Vietnam' },
    { publicId: 'vista_chinesa_xbaaf6', title: 'Rio', location: 'Brazil' },
    { publicId: 'toronto_cr3bim', title: 'CN Tower', location: 'Canada' },
    { publicId: 'taipei_101_q9vpgi', title: 'Taipei 101', location: 'Taiwan' },
    { publicId: 'taipei_1_z4tdm8', title: 'Xiangshan Park', location: 'Taiwan' },
    { publicId: 'taipei_2_gvlgcd', title: 'Xiangshan Park Basketball', location: 'Taiwan' },
    { publicId: 'skerwink_1_pfsbxx', title: 'Skerwink Trail 1', location: 'Canada' },
    { publicId: 'skerwink_2_fyusom', title: 'Skerwink Trail 2', location: 'Canada' },
    { publicId: 'seljalandsfoss_lewujm', title: 'Seljalandsfoss', location: 'Iceland' },
    { publicId: 'santa_teresa_u7abx6', title: 'Santa Teresa', location: 'Costa Rica' },
    { publicId: 'rj_r5gop8', title: 'Rio de Janeiro', location: 'Brazil' },
    { publicId: 'riverdale_ecv8w3', title: 'Riverdale', location: 'Canada' },
    { publicId: 'quetzal_nnhgq5', title: 'Quetzal', location: 'Costa Rica' },
    { publicId: 'puffins_os5bs7', title: 'Puffins', location: 'Canada' },
    { publicId: 'puffin_inb8w1', title: 'Puffin', location: 'Canada' },
    { publicId: 'nl_hut_w7jhh2', title: 'NL Hut', location: 'Canada' },
    { publicId: 'nl_fox_dqifei', title: 'NL Fox', location: 'Canada' },
    { publicId: 'nl_cliffs_wza10a', title: 'NL Cliffs', location: 'Canada' },
    { publicId: 'mono_ardilla_fhhvho', title: 'Mono Ardilla', location: 'Costa Rica' },
    { publicId: 'la_guaira_2_qwzm4p', title: 'La Guaira 2', location: 'Venezuela' },
    { publicId: 'la_guaira_1_ny9mrx', title: 'La Guaira 1', location: 'Venezuela' },
    { publicId: 'la_fortuna_ienfvf', title: 'La Fortuna', location: 'Costa Rica' },
    { publicId: 'jordan_river_npwxxb', title: 'Jordan River', location: 'Canada' },
    { publicId: 'jökulsárgljúfur_plpfiw', title: 'Jökulsárgljúfur', location: 'Iceland' },
    { publicId: 'hvalnes_dwljzw', title: 'Hvalnes', location: 'Iceland' },
    { publicId: 'hanoi_svgmlz', title: 'Hanoi', location: 'Vietnam' },
    { publicId: 'grand_palace_zsepyj', title: 'Grand Palace', location: 'Thailand' },
    { publicId: 'gran_roque_gtquuw', title: 'Gran Roque', location: 'Venezuela' },
    { publicId: 'espadilla_etvcx5', title: 'Espadilla', location: 'Costa Rica' },
    { publicId: 'el_tigre_og5sgo', title: 'El Tigre', location: 'Costa Rica' },
    { publicId: 'dos_mosquises_idvg5s', title: 'Dos Mosquises', location: 'Venezuela' },
    { publicId: 'cliffs_hgrldr', title: 'Cliffs', location: 'Iceland' },
    { publicId: 'candelita_collareja_kup2v0', title: 'Candelita Collareja', location: 'Costa Rica' },
    { publicId: 'bertioga_2_hrrh8y', title: 'Bertioga 2', location: 'Brazil' },
    { publicId: 'bertioga_1_h5av5y', title: 'Bertioga 1', location: 'Brazil' },
    { publicId: 'bangkok_ba6wsx', title: 'Bangkok', location: 'Thailand' },
    { publicId: 'banff_xcehev', title: 'Banff', location: 'Canada' },
    { publicId: 'arenal_neqrk3', title: 'Arenal', location: 'Costa Rica' },
    { publicId: 'trang_an_ksmprm', title: 'Trang An', location: 'Vietnam' },
    { publicId: 'trang_an_2_l0dwzi', title: 'Trang An 2', location: 'Vietnam' },
    { publicId: 'tam_coc_sunset_eazl6d', title: 'Tam Coc Sunset', location: 'Vietnam' },
    { publicId: 'pu_luong_valley_owtkpa', title: 'Pu Luong Valley', location: 'Vietnam' },
    { publicId: 'pu_luong_terraces_vwssrr', title: 'Pu Luong Terraces', location: 'Vietnam' },
    { publicId: 'palawan_expedition_xuicsl', title: 'Palawan Expedition', location: 'Philippines' },
    // { publicId: 'milky_way_eralm9', title: 'Milky Way', location: 'Iceland' },
    { publicId: 'hang_mua_viewpoint_zsg5rg', title: 'Hang Mua Viewpoint', location: 'Vietnam' },
    { publicId: 'ha_long_sqdk2m', title: 'Ha Long', location: 'Vietnam' },
    { publicId: 'coron_jkbqbl', title: 'Coron', location: 'Philippines' },
    { publicId: 'eclipse_yhv2sh', title: 'Eclipse', location: 'Canada' },
];
